### ISSUE TITLE
strips shebang lines

### ISSUE THREAD

**Issue by jelmer** [asottile/setup-py-upgrade#77]
It looks like setup-py-upgrade strips leading comments for python files:

```
# Some comment

setup(name="blala")
```

results in the comment being stripped.

**Comment by spookylukey** [comment]
Why shouldn't you have a shebang for setup.py? It's a perfectly valid script, and there may be other existing scripts that depend on being able to do `./setup.py`. It seems like it would make sense to preserve a shebang, or at least warn if the rewritten version is going to break something, rather than do so silently. Thanks for considering!

**Comment by asottile** [comment]
it's not supposed to be run directly
